### ISSUE TITLE
Feature-request: Automatic Restart

### ISSUE THREAD

**Issue by PandiSimon** [NIREKI/DockerDiscordBot#1]
### Hello,
I have an idea for your script. 
How about an automatic server restart. In principle, it "only" needs to stop, pull updates (if available) and start.
Would definitely be cool! Thanks ^^

**Comment by NIREKI** [comment]
Ist theoretisch leicht umzusetzen, aber finde ich im Discord Bot fehl am Platz und sehe das eher beim Image vom Server. Kann man aber auch einfach über ein eigenes Skript lösen, bzw. über einen cronjob der immer um 3 Uhr Nachts ausgelöst wird und dann `docker exec -it containername manager update` ausführt..

Wenn man das in den Container an sich integriert, dann könnte man sicherlich vorher noch checken, ob der Server leer ist, aber sehe das halt nicht beim Discord Bot.
